// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVfH_nVAqHt3vdSwpGXxHe4G--7v9py8',
    appId: '1:154183473342:web:c181799238c63e2b70e6ef',
    messagingSenderId: '154183473342',
    projectId: 'pill-pal-40808',
    authDomain: 'pill-pal-40808.firebaseapp.com',
    databaseURL: 'https://pill-pal-40808-default-rtdb.firebaseio.com',
    storageBucket: 'pill-pal-40808.firebasestorage.app',
    measurementId: 'G-7LGFSM8GSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHljR1Y3spuD0lFG_VCRAkqqPN8VUMzs',
    appId: '1:154183473342:android:9440fbd81eca163070e6ef',
    messagingSenderId: '154183473342',
    projectId: 'pill-pal-40808',
    databaseURL: 'https://pill-pal-40808-default-rtdb.firebaseio.com',
    storageBucket: 'pill-pal-40808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyixh5TKSn3d6u1et5N-Ped4IhkEvw98',
    appId: '1:154183473342:ios:f409a1bf723ed2b770e6ef',
    messagingSenderId: '154183473342',
    projectId: 'pill-pal-40808',
    databaseURL: 'https://pill-pal-40808-default-rtdb.firebaseio.com',
    storageBucket: 'pill-pal-40808.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyixh5TKSn3d6u1et5N-Ped4IhkEvw98',
    appId: '1:154183473342:ios:f409a1bf723ed2b770e6ef',
    messagingSenderId: '154183473342',
    projectId: 'pill-pal-40808',
    databaseURL: 'https://pill-pal-40808-default-rtdb.firebaseio.com',
    storageBucket: 'pill-pal-40808.firebasestorage.app',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrVfH_nVAqHt3vdSwpGXxHe4G--7v9py8',
    appId: '1:154183473342:web:8f2820cf4b3af9a270e6ef',
    messagingSenderId: '154183473342',
    projectId: 'pill-pal-40808',
    authDomain: 'pill-pal-40808.firebaseapp.com',
    databaseURL: 'https://pill-pal-40808-default-rtdb.firebaseio.com',
    storageBucket: 'pill-pal-40808.firebasestorage.app',
    measurementId: 'G-Q20BG9FQ0N',
  );
}
